language: node_js
node_js:
  - "stable"
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
